"""
Editor engine route definitions.

Routes: fiction_editing, outline_editing, character_development, rules_editing,
style_editing, series_editing, electronics, general_project, podcast_script,
proofreading, article_writing, content_analysis.
"""

from orchestrator.routes.route_schema import EngineType, Route

EDITOR_ROUTES = [
    Route(
        name="fiction_editing",
        description="Analyze, review, and edit fiction manuscripts: assess chapters for quality, redundancy, style compliance; write and rewrite prose; sync with outline; maintain voice and character consistency.",
        engine=EngineType.CUSTOM_AGENT,
        domains=["fiction", "writing", "story", "manuscript"],
        actions=["observation", "generation", "modification"],
        editor_types=["fiction"],
        requires_editor=True,
        editor_preference="require",
        context_boost=20,
        keywords=["chapter", "scene", "dialogue", "character", "plot", "manuscript", "story", "prose", "analyze", "review", "redundancy", "repetition"],
        priority=90,
        tools=["search_documents_tool", "get_document_content_tool", "search_segments_across_documents_tool"],
        tool_io_map={
            "search_documents_tool": "search_documents",
            "get_document_content_tool": "get_document_content",
            "search_segments_across_documents_tool": "search_segments_across_documents",
        },
        supports_hitl=True,
    ),
    Route(
        name="outline_editing",
        description="Edit story outlines: structure, act breaks, plot points.",
        engine=EngineType.CUSTOM_AGENT,
        domains=["fiction", "writing", "outline"],
        actions=["observation", "generation", "modification"],
        editor_types=["outline"],
        requires_editor=True,
        context_boost=20,
        keywords=["outline", "structure", "act", "plot points", "build an outline"],
        priority=88,
    ),
    Route(
        name="nonfiction_outline_editing",
        description="Edit and generate non-fiction outlines: section structure, hierarchy, coverage, and flow.",
        engine=EngineType.CUSTOM_AGENT,
        domains=["content", "writing", "outline", "nonfiction"],
        actions=["observation", "generation", "modification"],
        editor_types=["nfoutline"],
        requires_editor=True,
        context_boost=20,
        keywords=[
            "non-fiction outline",
            "nonfiction outline",
            "outline",
            "structure",
            "sections",
            "table of contents",
            "toc",
            "argument",
            "thesis",
            "restructure",
        ],
        priority=88,
    ),
    Route(
        name="character_development",
        description="Edit character documents and character sheets.",
        engine=EngineType.CUSTOM_AGENT,
        domains=["fiction", "writing", "character"],
        actions=["observation", "generation", "modification"],
        editor_types=["character"],
        requires_editor=True,
        context_boost=20,
        keywords=["character", "character sheet", "protagonist", "antagonist"],
        priority=88,
    ),
    Route(
        name="rules_editing",
        description="Edit worldbuilding rules, canon, and lore documents.",
        engine=EngineType.CUSTOM_AGENT,
        domains=["fiction", "writing", "worldbuilding"],
        actions=["observation", "generation", "modification"],
        editor_types=["rules"],
        requires_editor=True,
        context_boost=20,
        keywords=["rules", "worldbuilding", "canon", "magic system", "lore"],
        priority=88,
    ),
    Route(
        name="style_editing",
        description="Edit style guide and voice documents.",
        engine=EngineType.CUSTOM_AGENT,
        domains=["fiction", "writing", "style"],
        actions=["observation", "generation", "modification"],
        editor_types=["style"],
        requires_editor=True,
        context_boost=20,
        keywords=["style", "voice", "style guide"],
        priority=88,
    ),
    Route(
        name="series_editing",
        description="Edit series synopsis, book status, and series continuity.",
        engine=EngineType.CUSTOM_AGENT,
        domains=["fiction", "writing", "series"],
        actions=["observation", "generation", "modification"],
        editor_types=["series"],
        requires_editor=True,
        context_boost=20,
        keywords=["series", "synopsis", "book status", "series continuity", "future books"],
        priority=88,
    ),
    Route(
        name="electronics",
        description="Manage electronics project documents, circuits, and embedded systems.",
        engine=EngineType.CUSTOM_AGENT,
        domains=["electronics", "circuit", "embedded", "arduino", "esp32", "microcontroller"],
        actions=["observation", "generation", "modification", "analysis", "query", "management"],
        editor_types=["electronics"],
        requires_editor=True,
        context_boost=20,
        keywords=["electronics", "circuit", "arduino", "esp32", "raspberry pi", "microcontroller", "sensor", "resistor", "voltage", "pcb", "schematic", "firmware", "embedded"],
        priority=85,
    ),
    Route(
        name="general_project",
        description="Manage project plans, scope, timeline, and requirements.",
        engine=EngineType.CUSTOM_AGENT,
        domains=["general", "management"],
        actions=["observation", "generation", "modification", "analysis", "management"],
        editor_types=["project"],
        requires_editor=True,
        context_boost=15,
        keywords=["project plan", "scope", "timeline", "requirements", "tasks", "project", "planning", "design", "specification"],
        priority=80,
    ),
    Route(
        name="podcast_script",
        description="Edit podcast scripts and show notes.",
        engine=EngineType.CUSTOM_AGENT,
        domains=["content", "writing", "podcast"],
        actions=["observation", "generation", "modification"],
        editor_types=["podcast"],
        requires_editor=True,
        context_boost=20,
        keywords=["podcast", "script", "episode", "show notes"],
        priority=85,
    ),
    Route(
        name="proofreading",
        description="Proofread and fix grammar, spelling, and style in documents.",
        engine=EngineType.CUSTOM_AGENT,
        domains=["general", "writing"],
        actions=["observation", "modification"],
        editor_types=["fiction", "outline", "article", "blog", "substack"],
        context_boost=15,
        keywords=["proofread", "grammar", "spelling", "typos", "fix errors"],
        priority=75,
    ),
    Route(
        name="article_writing",
        description="Write and edit articles, Substack posts, and blog content.",
        engine=EngineType.CUSTOM_AGENT,
        domains=["fiction", "writing", "content"],
        actions=["observation", "generation", "modification"],
        editor_types=["article", "substack", "blog"],
        requires_editor=True,
        context_boost=20,
        keywords=[
            "article",
            "blog",
            "substack",
            "post",
            "fix",
            "edit",
            "modify",
            "rewrite",
            "revise",
            "improve",
            "update",
            "change",
            "address issues",
            "fill gaps",
        ],
        priority=88,
    ),
    Route(
        name="content_analysis",
        description=(
            "Analyze, summarize, compare, and critique the open non-fiction document (read-only; no editing). "
            "Use when a doc is open and the user wants assessment only (e.g. summarize, critique, identify gaps, review structure)."
        ),
        engine=EngineType.CUSTOM_AGENT,
        domains=["general", "analysis", "documents", "writing", "content"],
        actions=["analysis", "observation"],
        editor_types=["article", "blog", "substack"],
        requires_editor=True,
        editor_preference="require",
        context_boost=15,
        keywords=[
            "analyze", "analysis", "summarize", "summary", "critique",
            "find gaps", "identify gaps", "find differences", "find conflicts",
            "assess", "assessment", "evaluate", "review structure",
            "strengths", "weaknesses", "what's missing",
        ],
        priority=82,
    ),
]
