-- Skill promotion / demotion recommendations generated by the weekly analysis task.
-- A recommendation captures a suggested change to is_core status with evidence.
CREATE TABLE IF NOT EXISTS skill_promotion_recommendations (
    id          BIGSERIAL PRIMARY KEY,
    skill_id    UUID NOT NULL REFERENCES agent_skills(id) ON DELETE CASCADE,
    skill_slug  VARCHAR(100) NOT NULL,
    action      VARCHAR(10) NOT NULL CHECK (action IN ('promote', 'demote')),
    reason      TEXT NOT NULL,
    evidence    JSONB DEFAULT '{}',
    status      VARCHAR(10) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'applied', 'dismissed')),
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    resolved_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_skill_promo_recs_status
    ON skill_promotion_recommendations(status);
CREATE INDEX IF NOT EXISTS idx_skill_promo_recs_skill
    ON skill_promotion_recommendations(skill_id);
